name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      - name: Install luacheck
        uses: leafo/gh-actions-luarocks@v4
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Run luacheck
        run: luacheck lua/

  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install StyLua
        uses: actions/cache@v3
        id: stylua-cache
        with:
          path: ~/.cargo/bin/stylua
          key: ${{ runner.os }}-stylua-1.0.0
          
      - name: Install StyLua if not cached
        if: steps.stylua-cache.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: stylua --version=0.18.2
          
      - name: Run StyLua
        run: ~/.cargo/bin/stylua --check lua/

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Run Tests
        run: |
          nvim --headless -u NONE -c "lua package.path = './lua/?.lua;' .. package.path" -c "lua require('test.neo-slack_spec')" -c "q"